# Generated by Django 5.2.6 on 2026-03-02 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreamspharmaapp', '0018_salesorderitem_batch_no_salesorderitem_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('UPI', 'UPI')], default='RAZORPAY', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('PENDING', 'Payment Pending'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled'), ('REFUNDED', 'Payment Refunded')], default='INITIATED', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('customer_ip', models.GenericIPAddressField(blank=True, help_text='Customer IP address at time of payment', null=True)),
                ('customer_user_agent', models.CharField(blank=True, help_text='User browser/device info', max_length=500, null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of payment attempts')),
                ('merchant_reference_id', models.CharField(blank=True, help_text='Merchant reference for settlement', max_length=100, null=True, unique=True)),
                ('razorpay_fee', models.DecimalField(decimal_places=2, default=0, help_text='Razorpay processing fee', max_digits=12)),
                ('razorpay_tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax on processing fee', max_digits=12)),
                ('settlement_id', models.CharField(blank=True, help_text='Razorpay settlement ID', max_length=100, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, help_text='Payment settlement date', null=True)),
                ('is_settled', models.BooleanField(default=False, help_text='Is payment settled in merchant account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_at', models.DateTimeField(blank=True, help_text='Razorpay order expiry time (15 mins)', null=True)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dreamspharmaapp.salesorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATE_ORDER', 'Create Order'), ('VERIFY_PAYMENT', 'Verify Payment'), ('FETCH_ORDER', 'Fetch Order'), ('REFUND', 'Refund'), ('WEBHOOK', 'Webhook')], max_length=50)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('INITIATED', 'Refund Initiated'), ('PENDING', 'Refund Pending'), ('SUCCESS', 'Refund Successful'), ('FAILED', 'Refund Failed'), ('REJECTED', 'Refund Rejected')], default='INITIATED', max_length=20)),
                ('refund_type', models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund')], default='FULL', help_text='Full or partial refund', max_length=20)),
                ('request_notes', models.TextField(blank=True, null=True)),
                ('response_notes', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('initiated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payment_pay_payment_664ade_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='payment_pay_razorpa_31c701_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_payment_id'], name='payment_pay_razorpa_259e03_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payment_pay_user_id_2df5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant_reference_id'], name='payment_pay_merchan_da60c1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payment_pay_status_e53604_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_settled', '-settlement_date'], name='payment_pay_is_sett_8c6318_idx'),
        ),
    ]
