# Generated by Django 5.2.6 on 2026-02-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0011_alter_kyc_store_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Aadhar/PAN/Government ID number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Full name of the shop owner/customer', max_length=200, null=True),
        ),
    ]
