# Generated by Django 5.2.6 on 2026-02-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0012_kyc_customer_id_kyc_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='customer_name',
        ),
    ]
