# Generated by Django 5.2.6 on 2026-02-23 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0013_remove_kyc_customer_id_remove_kyc_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Aadhaar number or PAN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='customer_photo',
            field=models.FileField(blank=True, help_text='Customer profile photo', null=True, upload_to='kyc/customer_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
