# Generated by Django 5.2.6 on 2026-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0014_kyc_customer_id_kyc_customer_name_kyc_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING_OTP_VERIFICATION', 'Pending OTP Verification'), ('REGISTERED', 'Registered'), ('KYC_SUBMITTED', 'KYC Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved (by SuperAdmin)'), ('LOGIN_ENABLED', 'Login Enabled')], default='REGISTERED', max_length=30),
        ),
    ]
