# Generated by Django 5.2.6 on 2026-03-02 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0017_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='batch_no',
            field=models.CharField(blank=True, help_text='Medicine batch number for recall tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Medicine expiry date', null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of recipient', max_length=200)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Phone number must be 10-15 digits')])),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('locality', models.CharField(help_text='Locality/Area/Street', max_length=255)),
                ('flat_building', models.CharField(blank=True, help_text='Flat no/Building Name', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Landmark (optional)', max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office'), ('OTHER', 'Others')], default='HOME', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default delivery address')),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude from GPS/map', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude from GPS/map', max_digits=9, null=True)),
                ('location_accuracy', models.IntegerField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('is_gps_verified', models.BooleanField(default=False, help_text='Address confirmed via GPS coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'phone', 'pincode', 'locality')},
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Linked delivery address for this order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='dreamspharmaapp.address'),
        ),
    ]
