# Generated by Django 5.2.6 on 2026-03-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0018_salesorderitem_batch_no_salesorderitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='subheading',
            field=models.CharField(blank=True, help_text='Product subheading/subtitle for mobile app', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('image_order', models.PositiveIntegerField(default=1, help_text='Order of image display (1-3 for 3 main images)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dreamspharmaapp.productinfo')),
            ],
            options={
                'ordering': ['image_order'],
                'unique_together': {('product_info', 'image_order')},
            },
        ),
    ]
