# Generated by Django 5.2.6 on 2026-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0019_remove_productinfo_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture for user', null=True, upload_to='profiles/'),
        ),
    ]
