# Generated by Django 5.2.6 on 2026-03-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0021_remove_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand/Category name (e.g., Cipla, Mankind, Apollo Pharma)', max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Brand logo/icon for UI display', null=True, upload_to='categories/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories (Brands)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productinfo',
            name='type_label',
            field=models.CharField(blank=True, help_text="Product type label (e.g., 'Pain Relief', 'Antibiotic') shown under product name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Brand/Category assigned by superadmin (e.g., Cipla, Mankind)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dreamspharmaapp.category'),
        ),
    ]
