# Generated by Django 5.2.6 on 2026-04-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0024_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(help_text='Device registration token from Firebase', max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, help_text='e.g., ios, android, web', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the token still active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Offer title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed offer description', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('placement', models.CharField(choices=[('homepage', 'Homepage Banner'), ('category', 'Category Page')], default='homepage', help_text='Where offer appears', max_length=50)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for display', null=True, upload_to='offers/banners/')),
                ('status', models.BooleanField(default=True, help_text='Active/Inactive status')),
                ('valid_from', models.DateField(help_text='Offer start date')),
                ('valid_to', models.DateField(help_text='Offer end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category for category-specific offers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='dreamspharmaapp.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products for this offer (leave empty for all in category)', related_name='offers', to='dreamspharmaapp.itemmaster')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dreamspharm_status_dcb0e5_idx'), models.Index(fields=['valid_from', 'valid_to'], name='dreamspharm_valid_f_b9d489_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dreamspharmaapp.itemmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='dreamspharm_user_id_aa2c13_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
