# Generated by Django 5.2.6 on 2026-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0025_fcmdevice_offer_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='bill_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='br_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='c2_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='cust_code',
            field=models.CharField(blank=True, default='', help_text='Customer/Account code', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='cust_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ip_no',
            field=models.CharField(blank=True, default='', help_text='Patient/Customer IP number', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ord_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ord_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='patient_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='store_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sys_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sys_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sys_user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tran_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tran_srno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tran_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
