# Generated by Django 5.2.6 on 2026-04-10 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0026_alter_salesorder_bill_total_alter_salesorder_br_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(help_text='Notification title (e.g., offer name)', max_length=255)),
                ('message', models.TextField(help_text='Notification message/description')),
                ('is_read', models.BooleanField(default=False, help_text='Has retailer seen this notification?')),
                ('icon_url', models.CharField(blank=True, help_text='Icon URL for notification display', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dreamspharmaapp.offer')),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'RETAILER'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retailer Notification',
                'verbose_name_plural': 'Retailer Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['retailer', '-created_at'], name='dreamspharm_retaile_f16f14_idx'), models.Index(fields=['retailer', 'is_read'], name='dreamspharm_retaile_a22395_idx')],
            },
        ),
    ]
