# Generated by Django 5.2.6 on 2026-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0027_retailernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailernotification',
            name='notification_type',
            field=models.CharField(choices=[('OFFER', 'Offer/Discount'), ('BANNER', 'Banner'), ('PROMOTION', 'Promotion'), ('SYSTEM', 'System')], default='OFFER', help_text='Type of notification', max_length=20),
        ),
    ]
