# Generated by Django 5.2.6 on 2026-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0028_retailernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailernotification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Notification priority', max_length=10),
        ),
    ]
