# Generated by Django 6.0.4 on 2026-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0030_creditnote_retailerwallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(help_text='Unique store identifier from ERP', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(help_text='Store/Branch name', max_length=255)),
                ('pincode', models.CharField(db_index=True, help_text='Pincode of the store location', max_length=10)),
                ('city', models.CharField(help_text='City where store is located', max_length=100)),
                ('state', models.CharField(help_text='State where store is located', max_length=100)),
                ('address', models.TextField(help_text='Full address of the store')),
                ('latitude', models.FloatField(help_text='Latitude coordinate of store location')),
                ('longitude', models.FloatField(help_text='Longitude coordinate of store location')),
                ('phone', models.CharField(blank=True, help_text='Store contact number', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Store email address', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this store active for delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['store_name'],
                'indexes': [models.Index(fields=['pincode'], name='dreamspharm_pincode_442ed8_idx'), models.Index(fields=['latitude', 'longitude'], name='dreamspharm_latitud_963775_idx')],
            },
        ),
    ]
