# Generated by Django 5.2.6 on 2026-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0031_add_store_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price per item', max_digits=10),
        ),
    ]
