# Generated by Django 6.0.4 on 2026-05-02 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0032_delete_store_creditnote_sale_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(help_text='Which attempt (1-10)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking ERP'), ('found', 'Invoice Found'), ('not_ready', 'Not Ready Yet'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('next_check_at', models.DateTimeField(help_text='When to check again (exponential backoff: 5min, 10min, 20min...)')),
            ],
            options={
                'ordering': ['sales_order', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_disc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_qty', models.IntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires (5-10 min TTL)')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this cache is still valid')),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in this store (can vary by store)', max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Real-time stock count in this store')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock threshold')),
                ('is_available', models.BooleanField(default=True, help_text='Can customers order this in this store?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Store Variant',
                'verbose_name_plural': 'Product Store Variants',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Store name (e.g., DreamsPharma - Bangalore', max_length=255, unique=True)),
                ('address', models.TextField(help_text='Full address of the store')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, help_text='Store latitude (auto-geocoded from pincode if not provided)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Store longitude (auto-geocoded from pincode if not provided)', null=True)),
                ('c2_code', models.CharField(help_text='Unique C2 code for this store (e.g., 03C000)', max_length=20, unique=True)),
                ('store_id', models.CharField(help_text='Store ID for ERP (e.g., 001)', max_length=20, unique=True)),
                ('prod_code', models.CharField(default='02', help_text='Production code for ERP', max_length=20)),
                ('security_key', models.CharField(help_text='Security key for ERP API calls', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this store active for orders')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/default store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='store_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_latitude',
            field=models.FloatField(blank=True, help_text="User's last GPS latitude", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_longitude',
            field=models.FloatField(blank=True, help_text="User's last GPS longitude", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_pincode',
            field=models.CharField(blank=True, help_text="User's delivery pincode", max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='retailerwallet',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking on concurrent wallet updates'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async order processing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether order confirmation email was sent'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='erp_store_id',
            field=models.CharField(blank=True, default='', help_text='ERP Store ID (kept for legacy tracking)', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of times tried to fetch invoice (auto-retry max 10)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_sync_error',
            field=models.TextField(blank=True, help_text='Error message if invoice sync failed', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_sync_status',
            field=models.CharField(choices=[('pending', 'Pending Invoice'), ('syncing', 'Syncing with ERP'), ('found', 'Invoice Found'), ('failed', 'Sync Failed')], default='pending', help_text='Status of invoice retrieval from ERP', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_stock_reserved',
            field=models.BooleanField(default=False, help_text='Just metadata - actual locking handled by SELECT_FOR_UPDATE in checkout view'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='last_invoice_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last time invoice sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='When stock reservation was attempted', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='task_started_at',
            field=models.DateTimeField(blank=True, help_text='When async task started processing', null=True),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'updated_at'], name='dreamspharm_cart_id_660cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerwallet',
            index=models.Index(fields=['retailer'], name='dreamspharm_retaile_e0213e_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerwallet',
            index=models.Index(fields=['balance'], name='dreamspharm_balance_9992ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='retailerwallet',
            constraint=models.UniqueConstraint(fields=('retailer',), name='one_wallet_per_user'),
        ),
        migrations.AddField(
            model_name='invoicesynclog',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sync_logs', to='dreamspharmaapp.salesorder'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_variants', to='dreamspharmaapp.itemmaster'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'pincode'], name='dreamspharm_is_acti_4c1d5a_idx'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dreamspharmaapp.store'),
        ),
        migrations.AddField(
            model_name='productcache',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cache', to='dreamspharmaapp.store'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_store',
            field=models.ForeignKey(blank=True, help_text="User's nearest/preferred store for orders", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dreamspharmaapp.store'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Which store fulfilled this order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dreamspharmaapp.store'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'created_at'], name='dreamspharm_status_b61e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['store', 'status'], name='dreamspharm_store_i_da1938_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['user_id', 'created_at'], name='dreamspharm_user_id_f84569_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['invoice_sync_status'], name='dreamspharm_invoice_fa3f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['is_stock_reserved'], name='dreamspharm_is_stoc_ab2dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['c2_code', 'store_id', 'order_id'], name='dreamspharm_c2_code_fa3658_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('order_id', 'c2_code'), name='unique_order_per_erp_store'),
        ),
        migrations.AddIndex(
            model_name='invoicesynclog',
            index=models.Index(fields=['status', 'next_check_at'], name='dreamspharm_status_5d1231_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesynclog',
            index=models.Index(fields=['sales_order'], name='dreamspharm_sales_o_395d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['store', 'is_available'], name='dreamspharm_store_i_421482_idx'),
        ),
        migrations.AddIndex(
            model_name='productstore',
            index=models.Index(fields=['product', 'store'], name='dreamspharm_product_9f3e22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstore',
            unique_together={('product', 'store')},
        ),
        migrations.AddIndex(
            model_name='productcache',
            index=models.Index(fields=['store', 'is_valid', 'expires_at'], name='dreamspharm_store_i_76c7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='productcache',
            index=models.Index(fields=['item_code', 'store'], name='dreamspharm_item_co_6084a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcache',
            constraint=models.UniqueConstraint(fields=('item_code', 'store'), name='unique_product_per_store_cache'),
        ),
    ]
