# Generated by Django 6.0.4 on 2026-05-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0033_invoicesynclog_productcache_productstore_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='erp_store_id',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='erp_store_code',
            field=models.CharField(blank=True, default='', help_text='ERP Store code (legacy - for API response use store_id)', max_length=20),
        ),
    ]
