# Generated by Django 6.0.4 on 2026-05-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0034_remove_salesorder_erp_store_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesorder',
            name='dreamspharm_store_i_da1938_idx',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='store',
            new_name='fulfilling_store',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store_id',
            field=models.CharField(blank=True, default='', help_text='ERP Store ID for API responses and ERP integration', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['fulfilling_store', 'status'], name='dreamspharm_fulfill_d8c226_idx'),
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='erp_store_code',
        ),
    ]
