# Generated by Django 5.2.6 on 2026-05-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0035_remove_salesorder_dreamspharm_store_i_da1938_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='dreamspharmaapp.store'),
        ),
    ]
