# Generated by Django 5.2 on 2026-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0036_creditnote_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
