# Generated by Django 6.0.6 on 2026-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0099_salesorder_wallet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='brand_code',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='brand_name',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category_code',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category_name',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='content_code',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='content_name',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='hsn_sac_name',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_short_name',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='pack_code',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='pack_name',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
