# Generated by Django 6.0.6 on 2026-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0100_itemmaster_brand_code_itemmaster_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='erp_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of retry attempts to push order to ERP'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='erp_sync_error',
            field=models.TextField(blank=True, help_text='Error message if ERP order push failed', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='erp_sync_payload',
            field=models.JSONField(blank=True, help_text='Saved JSON payload used to re-push order to ERP when offline', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_erp_synced',
            field=models.BooleanField(default=False, help_text='Whether this order was successfully accepted by ERP server'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='last_erp_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last timestamp when ERP push retry was attempted', null=True),
        ),
    ]
