# Generated by Django 5.2.6 on 2026-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('USER', 'User/KYC'), ('ORDER', 'Order'), ('INVENTORY', 'Inventory/Stock'), ('PAYMENT', 'Payment'), ('PROMO', 'Promotion/Banner'), ('SYSTEM', 'System/Sync')], max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=15)),
                ('related_id', models.CharField(blank=True, help_text='ID of the related object (e.g., SalesOrder order_id, User ID)', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
