# Generated by Django 5.2.6 on 2026-04-07 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('action', models.CharField(max_length=255)),
                ('performed_by', models.CharField(default='System', max_length=255)),
                ('target_entity', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('KYC', 'KYC'), ('ERP', 'ERP'), ('Refund', 'Refund'), ('System', 'System'), ('Order', 'Order'), ('Category', 'Category'), ('Offer', 'Offer'), ('Product', 'Product')], default='System', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
