"""
Django settings for dreamspharma project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import sys
import logging

# Monkeypatch logging to prevent daemon threads from crashing during interpreter finalization
_original_handle = logging.Handler.handle
def _safe_handle(self, record):
    if sys.is_finalizing():
        return
    try:
        return _original_handle(self, record)
    except Exception:
        pass
logging.Handler.handle = _safe_handle


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v9div(*7#85s3qa+mt-wc%&&57s0sz5bpx4i-(h&)li__-1r*+'

# SECURITY WARNING: don't run with debug turned on in production!
CORS_ALLOW_ALL_ORIGINS = False
DEBUG = True

CORS_ALLOWED_ORIGINS = [
    "https://dreamspharma-web.vercel.app",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://localhost:60220",
    "http://127.0.0.1:60220",
    "http://localhost:54648",
]

CORS_ALLOW_CREDENTIALS = True
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'ngrok-skip-browser-warning',
]
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',  # Required for token rotation
    'django_apscheduler',
    'dreamspharmaapp',
    'maindash', 
    'payment',      

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'dreamspharmaapp.middleware.StoreContextMiddleware',  # ✓ Extract store context from location
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'dreamspharma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dreamspharma.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'dreamspharmaapp.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Public by default, override in views
    ),
    # ==================== RATE LIMITING ====================
    # ✅ PRODUCTION FIX #3: Prevent abuse and overload
    # Without rate limiting: 1 attacker × 1000 requests/sec = system crash
    # With rate limiting: 10 orders/min per user = controlled load
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10000/day',          # Anonymous users: Increased for development
        'user': '1000/hour',          # Authenticated users: 1000/hour (general)
        'orders': '10/minute',        # Order creation: 10 orders/minute per user
        'auth': '5/minute',           # Authentication: 5 attempts/minute
    }
}

# ==================== JWT SETTINGS ====================
# Industry-standard: Short access tokens + silent refresh
from datetime import timedelta

SIMPLE_JWT = {
    # Access token valid for 24 hours
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    
    # Long-lived refresh token (365 days) - user stays logged in year-long
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    
    # Rotate refresh tokens on every refresh (more secure)
    'ROTATE_REFRESH_TOKENS': True,
    
    # Blacklist old refresh tokens after rotation
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Update last login timestamp
    'UPDATE_LAST_LOGIN': True,
    
    # Algorithm
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    
    # Token headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    # User identification
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Token type claim
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==================== CELERY ASYNC TASK QUEUE ====================
# ✅ PRODUCTION FIX #4: Move heavy processes to background
# Without Celery: User waits for ERP API call (10 seconds!) → 100 users = timeout errors
# With Celery: Response returned instantly, ERP call happens in background
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Prevent one worker from hogging all tasks
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Prevent memory leaks in workers

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pharma',        
        'USER': 'postgres',      
        'PASSWORD': 'Soorya@123',
        'HOST': 'localhost',     
        'PORT': '5432',         
        # ==================== CONNECTION POOLING ====================
        # ✅ PRODUCTION FIX #1: Reuse database connections (prevents connection exhaustion)
        # Without this: Every request creates new DB connection → 100+ users = 100+ connections!
        # With this: Connection pool reuses existing connections → Massive performance boost
        'CONN_MAX_AGE': 0,  # Close connections immediately in development to prevent connection exhaustion
        'OPTIONS': {
            'connect_timeout': 10,
            'keepalives': 1,
            'keepalives_idle': 30,
        }
    }
}

# ==================== REDIS CACHE CONFIGURATION ====================
# ✅ PRODUCTION FIX #2: Persistent, shared cache using Redis
# - Survives server restarts (unlike LocMemCache)
# - Shared across all Gunicorn workers (unlike LocMemCache which is per-process)
# - ERP master data cached for 1 hour → eliminates repeated slow API calls
# - ERP stock data cached for 5 minutes → near-realtime without hammering ERP
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake-erp-cache',
        'TIMEOUT': 300,
    }
}

# ── ERP cache TTL constants (used by erp_redis_cache.py) ──────────────────────
ERP_MASTER_DATA_CACHE_TTL = int(os.environ.get('ERP_MASTER_DATA_CACHE_TTL', 3600))   # 1 hour
ERP_STOCK_CACHE_TTL       = int(os.environ.get('ERP_STOCK_CACHE_TTL', 300))          # 5 minutes
ERP_TOKEN_CACHE_TTL       = int(os.environ.get('ERP_TOKEN_CACHE_TTL', 86400))        # 24 hours
# DATABASES = {
#     'default': dj_database_url.parse("postgresql://postgres:db_dreamspharma@db.wdpwanzaoacvcyvdqeek.supabase.co:5432/postgres")
# }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




OTP_EXPIRY_TIME = 600  # 10 minutes in seconds


EMAIL_HOST='smtp.gmail.com'
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'heysoorya1@gmail.com')  # Use environment variable
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'ibot dfts yoke orsn')  # Use environment variable
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'sooryakr2004@gmail.com')  # Use environment variable


# ==================== ERP INTEGRATION ====================
# 🔧 MULTI-STORE CONFIGURATION
# ERP settings are now PER-STORE (stored in Store model)
# Each store has its own: c2_code, store_id, security_key
# Views fetch these from database instead of hardcoded values

ERP_BASE_URL = os.environ.get('ERP_BASE_URL', 'http://59.96.58.81:45501')  # ERP Server URL
 
# ⚠️ Fallback ERP settings (used when no stores in database)
# In production, these should be set via environment variables or Store model in database
ERP_C2_CODE = os.environ.get('ERP_C2_CODE', '0X1000')
ERP_STORE_ID = os.environ.get('ERP_STORE_ID', '501')
ERP_PROD_CODE = os.environ.get('ERP_PROD_CODE', '02')
ERP_SECURITY_KEY = os.environ.get('ERP_SECURITY_KEY', 'TUZneE5UQXhNalU9')

# Token refresh settings (in hours)
ERP_TOKEN_REFRESH_HOURS = 23  # Refresh token every 23 hours (before 24-hour expiry)


# ==================== SENTRY ERROR TRACKING ====================
# ✅ PRODUCTION FIX #7: Real-time error monitoring and alerting
# Without Sentry: Bugs go unnoticed until customers complain
# With Sentry: Bugs caught immediately with full stack trace, user context, release info
if not DEBUG:  # Only in production
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    
    sentry_sdk.init(
        dsn=os.environ.get('SENTRY_DSN', ''),  # Get from environment
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=0.1,  # 10% of transactions (reduce costs)
        send_default_pii=False,  # Don't send personal data
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        release=os.environ.get('APP_RELEASE', 'latest'),
    )


# ==================== APScheduler Configuration ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            '()': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
            'stream': 'ext://sys.stdout',
        },
        'pharmacy_orders_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'pharmacy_orders.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'apscheduler.schedulers.background': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'apscheduler.executors': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'apscheduler.jobstores': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'dreamspharmaapp': {
            'handlers': ['console', 'pharmacy_orders_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    }
}

# Create logs directory if it doesn't exist
import os
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# ==================== RAZORPAY PAYMENT SETTINGS ====================
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_SN2KVaGDoF3Mdz')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'e180zkNhC8ks54aeD0FuU9am')

# Razorpay Settings
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', 'your_webhook_secret')
